#include "pch.h"
#include "settings_dialog.h"

#include <winrt/Microsoft.UI.Xaml.Automation.h>
#include <winrt/Microsoft.UI.Composition.SystemBackdrops.h>
#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Windowing.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.Text.h>
#include <dwrite_1.h>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <vector>

using namespace winrt;
using namespace winrt::Microsoft::UI::Xaml;
using namespace winrt::Microsoft::UI::Xaml::Controls;

namespace ZigonautSettings {
namespace {

std::string trim(std::string value) {
    auto const first = value.find_first_not_of(" \t\r");
    if (first == std::string::npos) return {};
    auto const last = value.find_last_not_of(" \t\r");
    return value.substr(first, last - first + 1);
}

std::map<std::string, std::string> parse(std::string_view contents) {
    std::map<std::string, std::string> values;
    std::istringstream lines{std::string{contents}};
    for (std::string line; std::getline(lines, line);) {
        line = trim(std::move(line));
        if (line.empty() || line[0] == '#' || line[0] == ';') continue;
        auto const separator = line.find('=');
        if (separator == std::string::npos) continue;
        values[trim(line.substr(0, separator))] = trim(line.substr(separator + 1));
    }
    return values;
}

std::string profileText(std::string_view contents) {
    struct ProfileLine { std::string name; std::string value; };
    std::vector<ProfileLine> profiles;
    std::istringstream lines{std::string{contents}};
    for (std::string line; std::getline(lines, line);) {
        line = trim(std::move(line));
        if (!line.starts_with("profile.")) continue;
        auto const separator = line.find('=');
        if (separator == std::string::npos || separator <= 8) continue;
        profiles.push_back({trim(line.substr(8, separator - 8)), trim(line.substr(separator + 1))});
    }

    std::string result;
    auto append = [&result](std::string const& name, std::string const& profile) {
        if (!result.empty()) result += "\r\n";
        result += name + "|" + profile;
    };
    if (contents.find("# Generated by the Zigonaut settings page.") != std::string_view::npos) {
        static ProfileLine const defaults[] = {
            {"PowerShell", "powershell|powershell.exe"},
            {"WSL", "wsl|wsl.exe"},
            {"Command Prompt", "windows|cmd.exe"},
        };
        for (auto const& fallback : defaults) {
            auto configured = std::find_if(profiles.begin(), profiles.end(), [&](auto const& candidate) { return candidate.name == fallback.name; });
            append(fallback.name, configured == profiles.end() ? fallback.value : configured->value);
        }
        for (auto const& profile : profiles) {
            auto built_in = std::find_if(std::begin(defaults), std::end(defaults), [&](auto const& fallback) { return fallback.name == profile.name; });
            if (built_in == std::end(defaults)) append(profile.name, profile.value);
        }
        return result;
    }
    for (auto const& profile : profiles) append(profile.name, profile.value);
    return result;
}

std::string value(std::map<std::string, std::string> const& values, std::string const& key, std::string fallback = {}) {
    auto const found = values.find(key);
    return found == values.end() ? fallback : found->second;
}

TextBlock label(std::wstring_view text, std::wstring_view description = {}) {
    auto panel = TextBlock{};
    panel.Text(text);
    panel.FontWeight(Windows::UI::Text::FontWeights::SemiBold());
    if (!description.empty()) ToolTipService::SetToolTip(panel, box_value(description));
    return panel;
}

Border card(std::wstring_view title, std::wstring_view description, UIElement const& control, bool expanded = false) {
    auto text = StackPanel{};
    text.Spacing(4);
    auto heading = label(title, description);
    text.Children().Append(heading);
    if (!description.empty()) {
        auto detail = TextBlock{};
        detail.Text(description);
        detail.TextWrapping(TextWrapping::Wrap);
        detail.Opacity(0.72);
        detail.FontSize(12);
        text.Children().Append(detail);
    }

    auto layout = Grid{};
    layout.VerticalAlignment(VerticalAlignment::Top);
    layout.RowSpacing(expanded ? 8 : 0);
    auto header_row = RowDefinition{};
    header_row.Height(GridLength{1, GridUnitType::Auto});
    layout.RowDefinitions().Append(header_row);
    auto action_row = RowDefinition{};
    action_row.Height(GridLength{1, GridUnitType::Auto});
    layout.RowDefinitions().Append(action_row);
    auto text_column = ColumnDefinition{};
    text_column.Width(GridLength{1, GridUnitType::Star});
    layout.ColumnDefinitions().Append(text_column);
    auto action_column = ColumnDefinition{};
    action_column.Width(expanded ? GridLength{0, GridUnitType::Pixel} : GridLength{320, GridUnitType::Pixel});
    layout.ColumnDefinitions().Append(action_column);
    layout.Children().Append(text);
    auto element = control.as<FrameworkElement>();
    if (expanded) {
        Grid::SetRow(element, 1);
        Grid::SetColumnSpan(element, 2);
        element.Margin(Thickness{0});
    } else {
        Grid::SetColumn(element, 1);
        element.Margin(Thickness{24, 0, 0, 0});
        element.VerticalAlignment(VerticalAlignment::Center);
        layout.SizeChanged([element, action_column](auto const& sender, SizeChangedEventArgs const& args) {
            auto const wrapped = args.NewSize().Width <= 476;
            action_column.Width(wrapped ? GridLength{0, GridUnitType::Pixel} : GridLength{320, GridUnitType::Pixel});
            Grid::SetRow(element, wrapped ? 1 : 0);
            Grid::SetColumn(element, wrapped ? 0 : 1);
            Grid::SetColumnSpan(element, wrapped ? 2 : 1);
            element.Margin(wrapped ? Thickness{0} : Thickness{24, 0, 0, 0});
            element.HorizontalAlignment(HorizontalAlignment::Stretch);
            sender.as<Grid>().RowSpacing(wrapped ? 8 : 0);
        });
    }
    layout.Children().Append(control);

    auto result = Border{};
    result.Style(Application::Current().Resources().Lookup(box_value(L"ZigonautSettingsCardStyle")).as<Style>());
    result.Child(layout);
    return result;
}

TextBox textBox(std::string const& text, std::wstring_view placeholder = {}) {
    auto result = TextBox{};
    result.Text(to_hstring(text));
    result.PlaceholderText(placeholder);
    result.HorizontalAlignment(HorizontalAlignment::Stretch);
    return result;
}

NumberBox numberBox(std::string const& text, double fallback, double minimum, double maximum, double step = 1) {
    auto result = NumberBox{};
    try { result.Value(std::stod(text)); } catch (...) { result.Value(fallback); }
    result.Minimum(minimum);
    result.Maximum(maximum);
    result.SmallChange(step);
    result.SpinButtonPlacementMode(NumberBoxSpinButtonPlacementMode::Compact);
    return result;
}

ComboBox combo(std::string const& selected, std::initializer_list<std::wstring_view> choices) {
    auto result = ComboBox{};
    result.HorizontalAlignment(HorizontalAlignment::Stretch);
    int32_t index = 0;
    int32_t selected_index = 0;
    for (auto choice : choices) {
        result.Items().Append(box_value(choice));
        if (to_string(choice) == selected) selected_index = index;
        ++index;
    }
    result.SelectedIndex(selected_index);
    return result;
}

std::vector<std::wstring> monospaceFonts() {
    std::vector<std::wstring> result;
    com_ptr<IDWriteFactory> factory;
    check_hresult(DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, __uuidof(IDWriteFactory), reinterpret_cast<IUnknown**>(factory.put())));
    com_ptr<IDWriteFontCollection> collection;
    check_hresult(factory->GetSystemFontCollection(collection.put()));

    for (UINT32 index = 0; index < collection->GetFontFamilyCount(); ++index) {
        IDWriteFontFamily* family{};
        if (FAILED(collection->GetFontFamily(index, &family))) continue;
        IDWriteFont* font{};
        auto const font_result = family->GetFirstMatchingFont(DWRITE_FONT_WEIGHT_NORMAL, DWRITE_FONT_STRETCH_NORMAL, DWRITE_FONT_STYLE_NORMAL, &font);
        if (FAILED(font_result)) { family->Release(); continue; }
        IDWriteFont1* font1{};
        auto const monospaced = SUCCEEDED(font->QueryInterface(&font1)) && font1->IsMonospacedFont();
        if (font1) font1->Release();
        font->Release();
        if (!monospaced) { family->Release(); continue; }

        IDWriteLocalizedStrings* names{};
        if (SUCCEEDED(family->GetFamilyNames(&names))) {
            UINT32 name_index{};
            BOOL exists{};
            if (FAILED(names->FindLocaleName(L"en-us", &name_index, &exists)) || !exists) name_index = 0;
            UINT32 length{};
            if (SUCCEEDED(names->GetStringLength(name_index, &length))) {
                std::wstring name(length + 1, L'\0');
                if (SUCCEEDED(names->GetString(name_index, name.data(), length + 1))) {
                    name.resize(length);
                    result.push_back(std::move(name));
                }
            }
            names->Release();
        }
        family->Release();
    }
    std::sort(result.begin(), result.end());
    result.erase(std::unique(result.begin(), result.end()), result.end());
    return result;
}

ComboBox fontCombo(std::string const& selected) {
    auto result = ComboBox{};
    result.HorizontalAlignment(HorizontalAlignment::Stretch);
    auto choices = monospaceFonts();
    auto const selected_name = to_hstring(selected);
    if (std::find(choices.begin(), choices.end(), selected_name.c_str()) == choices.end()) choices.push_back(selected_name.c_str());
    std::sort(choices.begin(), choices.end());
    for (size_t index = 0; index < choices.size(); ++index) {
        result.Items().Append(box_value(choices[index]));
        if (choices[index] == selected_name.c_str()) result.SelectedIndex(static_cast<int32_t>(index));
    }
    return result;
}

ToggleSwitch toggle(std::string const& selected) {
    auto result = ToggleSwitch{};
    result.IsOn(selected == "true");
    result.OnContent(box_value(L"On"));
    result.OffContent(box_value(L"Off"));
    return result;
}

std::string colorOrEmpty(std::map<std::string, std::string> const& values, std::string const& key) {
    auto result = value(values, key);
    return result.size() == 7 && result[0] == '#' ? result : std::string{};
}

bool validColor(std::string const& color) {
    if (color.empty()) return true;
    if (color.size() != 7 || color[0] != '#') return false;
    return color.find_first_not_of("0123456789abcdefABCDEF", 1) == std::string::npos;
}

} // namespace

struct Dialog {
    Window window{nullptr};
    Grid root{nullptr};
    NavigationView navigation{nullptr};
    InfoBar error{nullptr};
    std::vector<ScrollViewer> pages;
    std::filesystem::path path;
    std::function<void()> saved;
    bool open = true;

    TextBox dark_theme{nullptr}, light_theme{nullptr};
    ComboBox font_family{nullptr};
    NumberBox font_size{nullptr}, scrollback_size{nullptr}, padding_horizontal{nullptr}, padding_vertical{nullptr}, opacity{nullptr};
    ComboBox color_scheme{nullptr}, backdrop{nullptr};
    ToggleSwitch random_background{nullptr};
    std::vector<TextBox> colors;

    TextBox default_profile{nullptr}, profiles{nullptr}, working_directory{nullptr};
    ToggleSwitch hold_on_exit{nullptr};
    ToggleSwitch clipboard_write{nullptr};
    NumberBox clipboard_limit{nullptr};
    TextBox pipe_command{nullptr};

    Window::Closed_revoker closed_revoker{};
    NavigationView::SelectionChanged_revoker navigation_revoker{};

    Dialog(std::string_view config_path, std::string_view contents, bool high_contrast, bool dark_theme, std::function<void()> on_saved)
        : path(to_hstring(config_path).c_str()), saved(std::move(on_saved)) {
        auto const values = parse(contents);
        window = Window{};
        window.Title(L"Zigonaut Settings");
        HWND settings_window{};
        check_hresult(window.as<::IWindowNative>()->get_WindowHandle(&settings_window));
        auto const app_icon = LoadIconW(GetModuleHandleW(nullptr), MAKEINTRESOURCEW(1));
        if (app_icon) {
            SendMessageW(settings_window, WM_SETICON, ICON_BIG, reinterpret_cast<LPARAM>(app_icon));
            SendMessageW(settings_window, WM_SETICON, ICON_SMALL, reinterpret_cast<LPARAM>(app_icon));
        }
        auto const dpi = GetDpiForWindow(settings_window);
        auto const app_window = window.AppWindow();
        auto const work_area = Microsoft::UI::Windowing::DisplayArea::GetFromWindowId(
            app_window.Id(), Microsoft::UI::Windowing::DisplayAreaFallback::Nearest).WorkArea();
        auto const inset = MulDiv(24, dpi, 96);
        auto const available_width = std::max(1, work_area.Width - inset * 2);
        auto const available_height = std::max(1, work_area.Height - inset * 2);
        auto const width = std::min(MulDiv(1200, dpi, 96), available_width);
        auto const height = std::min(MulDiv(800, dpi, 96), available_height);
        app_window.MoveAndResize({
            work_area.X + (work_area.Width - width) / 2,
            work_area.Y + (work_area.Height - height) / 2,
            width,
            height,
        });
        auto backdrop = Media::MicaBackdrop{};
        backdrop.Kind(Microsoft::UI::Composition::SystemBackdrops::MicaKind::Base);
        window.SystemBackdrop(backdrop);

        root = Grid{};
        auto error_row = RowDefinition{};
        error_row.Height(GridLength{1, GridUnitType::Auto});
        root.RowDefinitions().Append(error_row);
        auto content_row = RowDefinition{};
        content_row.Height(GridLength{1, GridUnitType::Star});
        root.RowDefinitions().Append(content_row);

        error = InfoBar{};
        error.Severity(InfoBarSeverity::Error);
        error.IsOpen(false);
        error.IsClosable(true);
        Grid::SetRow(error, 0);
        root.Children().Append(error);

        navigation = NavigationView{};
        navigation.PaneDisplayMode(NavigationViewPaneDisplayMode::Auto);
        navigation.IsBackButtonVisible(NavigationViewBackButtonVisible::Collapsed);
        navigation.IsSettingsVisible(false);
        navigation.OpenPaneLength(220);
        navigation.PaneTitle(L"Settings");
        Grid::SetRow(navigation, 1);

        auto add_navigation = [this](std::wstring_view title, wchar_t const* glyph) {
            auto item = NavigationViewItem{};
            item.Content(box_value(title));
            auto icon = FontIcon{};
            icon.Glyph(glyph);
            item.Icon(icon);
            navigation.MenuItems().Append(item);
            return item;
        };
        auto appearance_item = add_navigation(L"Appearance", L"\xE790");
        add_navigation(L"Terminal", L"\xE756");
        add_navigation(L"Profiles", L"\xE77B");
        add_navigation(L"Advanced", L"\xE713");

        pages.push_back(makeAppearance(values));
        pages.push_back(makeTerminal(values));
        pages.push_back(makeProfiles(values, profileText(contents)));
        pages.push_back(makeAdvanced(values));
        navigation.Content(pages[0]);
        navigation.SelectedItem(appearance_item);
        navigation_revoker = navigation.SelectionChanged(auto_revoke, [this](auto const&, NavigationViewSelectionChangedEventArgs const& args) {
            uint32_t index{};
            if (navigation.MenuItems().IndexOf(args.SelectedItem(), index) && index < pages.size()) navigation.Content(pages[index]);
        });
        root.Children().Append(navigation);
        window.Content(root);
        applyTheme(high_contrast, dark_theme);
        closed_revoker = window.Closed(auto_revoke, [this](auto const&, auto const&) { open = false; });
        registerAutoSave();
    }

    ScrollViewer page(std::wstring_view title, std::wstring_view description, std::vector<Border> const& section_cards) {
        auto panel = StackPanel{};
        panel.Spacing(12);
        panel.Padding(Thickness{0, 24, 0, 36});
        panel.MaxWidth(1064);
        panel.HorizontalAlignment(HorizontalAlignment::Stretch);
        auto heading = TextBlock{};
        heading.Text(title);
        heading.Style(Application::Current().Resources().Lookup(box_value(L"TitleTextBlockStyle")).as<Style>());
        panel.Children().Append(heading);
        auto detail = TextBlock{};
        detail.Text(description);
        detail.TextWrapping(TextWrapping::Wrap);
        detail.Opacity(0.72);
        panel.Children().Append(detail);
        auto automatic = TextBlock{};
        automatic.Text(L"Changes are saved and applied automatically.");
        automatic.TextWrapping(TextWrapping::Wrap);
        automatic.Opacity(0.72);
        automatic.FontSize(12);
        panel.Children().Append(automatic);
        auto card_stack = StackPanel{};
        card_stack.Spacing(4);
        for (auto const& item : section_cards) {
            card_stack.Children().Append(item);
        }
        panel.Children().Append(card_stack);
        auto scroll = ScrollViewer{};
        scroll.Content(panel);
        scroll.Padding(Thickness{36, 0, 36, 0});
        scroll.HorizontalContentAlignment(HorizontalAlignment::Stretch);
        scroll.HorizontalScrollBarVisibility(ScrollBarVisibility::Disabled);
        scroll.VerticalScrollBarVisibility(ScrollBarVisibility::Auto);
        return scroll;
    }

    ScrollViewer makeAppearance(std::map<std::string, std::string> const& values) {
        auto const scheme = value(values, "color_scheme", "system");
        color_scheme = combo("", {L"Use system setting", L"Light", L"Dark"});
        color_scheme.SelectedIndex(scheme == "light" ? 1 : scheme == "dark" ? 2 : 0);
        auto const material = value(values, "backdrop", "mica");
        backdrop = combo("", {L"None", L"Mica", L"MicaAlt", L"Acrylic"});
        backdrop.SelectedIndex(material == "none" ? 0 : material == "mica_alt" ? 2 : material == "acrylic" ? 3 : 1);
        dark_theme = textBox(value(values, "dark_theme", value(values, "theme", "rasmus")), L"rasmus");
        light_theme = textBox(value(values, "light_theme", "campbell-light"), L"campbell-light");
        opacity = numberBox(value(values, "background_opacity", "100"), 100, 0, 100);
        random_background = toggle(value(values, "randomize_tab_background", "true"));

        auto theme_grid = StackPanel{};
        theme_grid.Spacing(8);
        theme_grid.Children().Append(label(L"Dark theme")); theme_grid.Children().Append(dark_theme);
        theme_grid.Children().Append(label(L"Light theme")); theme_grid.Children().Append(light_theme);
        return page(L"Appearance", L"Choose how Zigonaut and terminal sessions look.", {
            card(L"Application theme", L"Follow Windows or always use a light or dark color scheme.", color_scheme),
            card(L"Window material", L"Choose the Fluent backdrop used behind the terminal.", backdrop),
            card(L"Terminal themes", L"Theme names are loaded from the themes folder beside Zigonaut.", theme_grid, true),
            card(L"Background opacity", L"Percentage opacity for the terminal background.", opacity),
            card(L"Random tab colors", L"Give each new tab a background hue with the same perceived brightness.", random_background),
        });
    }

    ScrollViewer makeTerminal(std::map<std::string, std::string> const& values) {
        font_family = fontCombo(value(values, "font_family", "Cascadia Mono"));
        font_size = numberBox(value(values, "font_size", "18"), 18, 6, 72);
        scrollback_size = numberBox(value(values, "scrollback_size", "10000"), 10000, 0, 1000000, 1000);
        padding_horizontal = numberBox(value(values, "padding_horizontal", "8"), 8, 0, 128);
        padding_vertical = numberBox(value(values, "padding_vertical", "8"), 8, 0, 128);
        auto font = StackPanel{}; font.Spacing(8);
        font.Children().Append(label(L"Font family")); font.Children().Append(font_family);
        font.Children().Append(label(L"Size (points)")); font.Children().Append(font_size);
        auto padding = StackPanel{}; padding.Spacing(8);
        padding.Children().Append(label(L"Horizontal (pixels)")); padding.Children().Append(padding_horizontal);
        padding.Children().Append(label(L"Vertical (pixels)")); padding.Children().Append(padding_vertical);

        colors.reserve(19);
        auto palette = StackPanel{}; palette.Spacing(8);
        static wchar_t const* names[] = { L"Foreground", L"Background", L"Cursor", L"ANSI 0 · Black", L"ANSI 1 · Red", L"ANSI 2 · Green", L"ANSI 3 · Yellow", L"ANSI 4 · Blue", L"ANSI 5 · Magenta", L"ANSI 6 · Cyan", L"ANSI 7 · White", L"ANSI 8 · Bright black", L"ANSI 9 · Bright red", L"ANSI 10 · Bright green", L"ANSI 11 · Bright yellow", L"ANSI 12 · Bright blue", L"ANSI 13 · Bright magenta", L"ANSI 14 · Bright cyan", L"ANSI 15 · Bright white" };
        for (size_t index = 0; index < 19; ++index) {
            auto const key = index == 0 ? "foreground" : index == 1 ? "background" : index == 2 ? "cursor" : "ansi" + std::to_string(index - 3);
            auto editor = textBox(colorOrEmpty(values, key), L"Use theme default (#RRGGBB)");
            palette.Children().Append(label(names[index]));
            palette.Children().Append(editor);
            colors.push_back(editor);
        }
        return page(L"Terminal", L"Configure text rendering, spacing, and optional palette overrides.", {
            card(L"Font", L"Use an installed monospace font family.", font, true),
            card(L"Scrollback size", L"Maximum number of history lines kept for new terminal sessions.", scrollback_size),
            card(L"Padding", L"Space between terminal cells and the pane edge.", padding, true),
            card(L"Palette overrides", L"Leave a field empty to use the selected theme. Colors use #RRGGBB.", palette, true),
        });
    }

    ScrollViewer makeProfiles(std::map<std::string, std::string> const& values, std::string profile_text) {
        default_profile = textBox(value(values, "default_profile", "PowerShell"), L"PowerShell");
        if (profile_text.empty()) profile_text = "PowerShell|powershell|powershell.exe\r\nWSL|wsl|wsl.exe\r\nCommand Prompt|windows|cmd.exe";
        profiles = TextBox{};
        profiles.AcceptsReturn(true);
        profiles.Text(to_hstring(profile_text));
        profiles.HorizontalAlignment(HorizontalAlignment::Stretch);
        profiles.TextWrapping(TextWrapping::NoWrap);
        profiles.MinHeight(180);
        profiles.FontFamily(Media::FontFamily{L"Cascadia Mono"});
        working_directory = textBox(value(values, "working_directory"), L"User home directory");
        hold_on_exit = toggle(value(values, "hold_on_exit", "false"));
        return page(L"Profiles", L"Manage the shells available from the new-tab menu.", {
            card(L"Default profile", L"The profile opened at startup and by Ctrl+Shift+T.", default_profile),
            card(L"Launch profiles", L"One per line: name|shell type|command. Shell type must be powershell, windows, or wsl.", profiles, true),
            card(L"Working directory", L"Leave empty to use your Windows home directory.", working_directory),
            card(L"Keep tabs open", L"Keep a new tab open after its process exits cleanly.", hold_on_exit),
        });
    }

    ScrollViewer makeAdvanced(std::map<std::string, std::string> const& values) {
        clipboard_write = toggle(value(values, "osc52_clipboard_write", "false"));
        clipboard_limit = numberBox(value(values, "osc52_clipboard_max_bytes", "1048576"), 1048576, 1, 16777216, 1024);
        pipe_command = textBox(value(values, "pipe_command_output"), L"Copy output to the clipboard");
        return page(L"Advanced", L"Security-sensitive terminal integration settings.", {
            card(L"Terminal clipboard writes", L"Allow OSC 52 and OSC 1337 Copy sequences to write to the Windows clipboard.", clipboard_write),
            card(L"Clipboard payload limit", L"Maximum decoded terminal clipboard payload in bytes.", clipboard_limit),
            card(L"Pipe command output", L"Windows command that receives the latest OSC 133 command output on stdin. Leave empty to copy it.", pipe_command),
        });
    }

    std::string serialize() {
        auto string = [](TextBox const& box) { return trim(to_string(box.Text())); };
        auto const selected_font = trim(to_string(unbox_value<hstring>(font_family.SelectedItem())));
        if (selected_font.empty()) throw std::runtime_error("Font family cannot be empty.");
        if (string(dark_theme).empty() || string(light_theme).empty()) throw std::runtime_error("Theme names cannot be empty.");
        for (auto const& editor : colors) if (!validColor(string(editor))) throw std::runtime_error("Palette colors must be empty or use #RRGGBB.");

        std::vector<std::string> profile_lines;
        std::istringstream lines{to_string(profiles.Text())};
        for (std::string line; std::getline(lines, line);) {
            line = trim(std::move(line));
            if (line.empty()) continue;
            auto first = line.find('|');
            auto second = first == std::string::npos ? first : line.find('|', first + 1);
            if (first == std::string::npos || second == std::string::npos || first == 0 || second == first + 1 || second + 1 == line.size())
                throw std::runtime_error("Every profile must use name|shell type|command.");
            auto kind = trim(line.substr(first + 1, second - first - 1));
            if (kind != "powershell" && kind != "windows" && kind != "wsl") throw std::runtime_error("Profile shell types must be powershell, windows, or wsl.");
            profile_lines.push_back(line);
        }
        if (profile_lines.empty() || profile_lines.size() > 32) throw std::runtime_error("Add between 1 and 32 profiles.");

        std::ostringstream output;
        output << "# Zigonaut configuration\n# Generated by the Zigonaut settings page.\n\n";
        output << "font_family=" << selected_font << '\n';
        output << "font_size=" << static_cast<unsigned>(font_size.Value()) << '\n';
        output << "scrollback_size=" << static_cast<unsigned>(scrollback_size.Value()) << '\n';
        output << "dark_theme=" << string(dark_theme) << '\n';
        output << "light_theme=" << string(light_theme) << '\n';
        output << "color_scheme=" << (color_scheme.SelectedIndex() == 1 ? "light" : color_scheme.SelectedIndex() == 2 ? "dark" : "system") << '\n';
        output << "padding_horizontal=" << static_cast<unsigned>(padding_horizontal.Value()) << '\n';
        output << "padding_vertical=" << static_cast<unsigned>(padding_vertical.Value()) << '\n';
        output << "background_opacity=" << static_cast<unsigned>(opacity.Value()) << '\n';
        output << "backdrop=" << (backdrop.SelectedIndex() == 0 ? "none" : backdrop.SelectedIndex() == 2 ? "mica_alt" : backdrop.SelectedIndex() == 3 ? "acrylic" : "mica") << "\n\n";
        static char const* keys[] = { "foreground", "background", "cursor", "ansi0", "ansi1", "ansi2", "ansi3", "ansi4", "ansi5", "ansi6", "ansi7", "ansi8", "ansi9", "ansi10", "ansi11", "ansi12", "ansi13", "ansi14", "ansi15" };
        for (size_t index = 0; index < colors.size(); ++index) if (!string(colors[index]).empty()) output << keys[index] << '=' << string(colors[index]) << '\n';
        output << "\ndefault_profile=" << string(default_profile) << '\n';
        for (auto const& profile : profile_lines) {
            auto const split = profile.find('|');
            output << "profile." << trim(profile.substr(0, split)) << '=' << trim(profile.substr(split + 1)) << '\n';
        }
        output << "working_directory=" << string(working_directory) << '\n';
        output << "hold_on_exit=" << (hold_on_exit.IsOn() ? "true" : "false") << '\n';
        output << "randomize_tab_background=" << (random_background.IsOn() ? "true" : "false") << '\n';
        output << "osc52_clipboard_write=" << (clipboard_write.IsOn() ? "true" : "false") << '\n';
        output << "osc52_clipboard_max_bytes=" << static_cast<unsigned>(clipboard_limit.Value()) << '\n';
        output << "pipe_command_output=" << string(pipe_command) << '\n';
        return output.str();
    }

    void save() noexcept {
        try {
            auto output = serialize();
            auto temporary = path;
            temporary.concat(L".tmp");
            {
                std::ofstream file{temporary, std::ios::binary | std::ios::trunc};
                if (!file || !(file << output)) throw std::runtime_error("Unable to write the configuration file.");
            }
            if (!MoveFileExW(temporary.c_str(), path.c_str(), MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
                std::filesystem::remove(temporary);
                throw std::runtime_error("Unable to replace the configuration file.");
            }
            error.IsOpen(false);
            if (saved) saved();
        } catch (std::exception const& exception) {
            error.Message(to_hstring(exception.what()));
            error.IsOpen(true);
        }
    }

    void registerAutoSave() {
        auto text_committed = [this](auto const&, auto const&) { save(); };
        for (auto const& editor : {dark_theme, light_theme, default_profile, profiles, working_directory, pipe_command})
            editor.LostFocus(text_committed);
        for (auto const& editor : colors) editor.LostFocus(text_committed);
        auto number_changed = [this](auto const&, auto const&) { save(); };
        for (auto const& editor : {font_size, scrollback_size, padding_horizontal, padding_vertical, opacity, clipboard_limit})
            editor.ValueChanged(number_changed);
        auto selection_changed = [this](auto const&, auto const&) { save(); };
        color_scheme.SelectionChanged(selection_changed);
        backdrop.SelectionChanged(selection_changed);
        font_family.SelectionChanged(selection_changed);
        auto toggled = [this](auto const&, auto const&) { save(); };
        for (auto const& editor : {random_background, hold_on_exit, clipboard_write}) editor.Toggled(toggled);
    }

    void applyTheme(bool high_contrast, bool dark_theme) {
        root.RequestedTheme(high_contrast ? ElementTheme::Default : dark_theme ? ElementTheme::Dark : ElementTheme::Light);
        window.AppWindow().TitleBar().PreferredTheme(high_contrast
            ? Microsoft::UI::Windowing::TitleBarTheme::UseDefaultAppMode
            : dark_theme ? Microsoft::UI::Windowing::TitleBarTheme::Dark
                         : Microsoft::UI::Windowing::TitleBarTheme::Light);
    }
};

std::shared_ptr<Dialog> show(std::string_view path, std::string_view contents, bool high_contrast, bool dark_theme, std::function<void()> saved) {
    auto result = std::make_shared<Dialog>(path, contents, high_contrast, dark_theme, std::move(saved));
    result->window.Activate();
    return result;
}

bool isOpen(std::shared_ptr<Dialog> const& dialog) noexcept {
    return dialog && dialog->open;
}

void activate(std::shared_ptr<Dialog> const& dialog) {
    if (isOpen(dialog)) dialog->window.Activate();
}

void setTheme(std::shared_ptr<Dialog> const& dialog, bool high_contrast, bool dark_theme) {
    if (isOpen(dialog)) dialog->applyTheme(high_contrast, dark_theme);
}

void close(std::shared_ptr<Dialog> const& dialog) {
    if (isOpen(dialog)) dialog->window.Close();
}

}
