name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  windows:
    name: Windows (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: windows-2025
            target: x86_64-windows
          - arch: arm64
            runner: windows-11-arm
            target: aarch64-windows

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run tests
        run: zig build test -Dtarget=${{ matrix.target }}

      - name: Compile
        run: zig build check -Dtarget=${{ matrix.target }}
